# Restart webpack-dev-server if you make changes here
default: &default
  enabled: true
  host: 192.168.33.10 
  port: 8080

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
